services:
  data-ingestion:
    build:
      context: ./data-ingestion-service
    ports:
      - "5000:5000"
    networks:
      - bot-network

  bot-detection:
    build:
      context: ./bot-detection-service
    ports:
      - "5001:5001"
    depends_on:
      - data-ingestion
    networks:
      - bot-network

networks:
  bot-network: