version: '3.8'

services:
  data-ingestion:
    build:
      context: ./data-ingestion-service
    ports:
      - "5000:5000"
    networks:
      - bot-network

  bot-detection:
    build:
      context: ./bot-detection-service
    ports:
      - "5001:5001"
    networks:
      - bot-network

  data-visualization:
    build:
      context: ./data-visualization-service
    ports:
      - "5002:5002"
    networks:
      - bot-network

networks:
  bot-network: