name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Шаг 3: Установка Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Шаг 4: Запуск сервисов через Docker Compose
      - name: Start services with Docker Compose
        run: |
          docker-compose up -d --build

      # Шаг 5: Ждем, пока сервисы запустятся
      - name: Wait for services to start
        run: |
          echo "Waiting for services to start..."
          sleep 30  # Увеличено время ожидания

      # Шаг 6: Проверка состояния сервисов
      - name: Check service status
        run: |
          echo "Checking if services are up..."
          DATA_INGESTION_STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:5000/data)
          BOT_DETECTION_STATUS=$(curl -o /dev/null -s -w "%{http_code}" -X POST -d '{"data": "test"}' http://localhost:5001/detect)

          if [ "$DATA_INGESTION_STATUS" -ne 200 ]; then
            echo "data-ingestion-service returned status code $DATA_INGESTION_STATUS"
            exit 1
          fi

          if [ "$BOT_DETECTION_STATUS" -ne 200 ]; then
            echo "bot-detection-service returned status code $BOT_DETECTION_STATUS"
            exit 1
          fi

      # Шаг 7: Вывод логов в случае ошибки
      - name: Debug service logs
        if: failure()
        run: |
          docker-compose logs data-ingestion
          docker-compose logs bot-detection

      # Шаг 8: Запуск интеграционных тестов
      - name: Run integration tests
        run: |
          python -m unittest discover tests

      # Шаг 9: Остановка контейнеров после тестов
      - name: Stop services with Docker Compose
        if: always()
        run: |
          docker-compose down

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Вход в Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Шаг 2: Публикация Docker-образов
      - name: Push Docker images to Docker Hub
        run: |
          docker tag data-ingestion-service ${{ secrets.DOCKERHUB_USERNAME }}/data-ingestion-service:latest
          docker tag bot-detection-service ${{ secrets.DOCKERHUB_USERNAME }}/bot-detection-service:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/data-ingestion-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bot-detection-service:latest